name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore src/RestClient.Net/RestClient.Net.csproj
    - name: Build
      run: dotnet build src/RestClient.Net/RestClient.Net.csproj --configuration Release --no-restore --framework:netcoreapp3.0
    - name: Test
      run: dotnet test src/RestClient.Net/RestClient.Net.csproj --no-restore --verbosity normal --framework:netcoreapp3.1
